routes/web.php
<?php

// Snippet for seeing all the database queries. 
//DB::listen(function($query){var_dump($query->sql, $query->bindings);});
//auth()->loginUsingId(6); // This is to spoof the user being logged in and used for testing

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home view not using auth, no sign-in required, splash page. 
Route::get('/', function () {
    return view('welcome');
});

// These routes require and use auth middleware and require a sign-in.
Route::middleware('auth')->group(function(){
	
	// TWeets main page, all tweets.
	Route::get('/tweets/', 'TweetsController@index')
		->name('home');
	
	// Store a new tweet
	Route::post('/tweets/', 'TweetsController@store');

	// Delete a tweet
	Route::delete('/tweets/{tweet}/delete/','TweetsController@destroy')
		->name('destroy_tweet');

	// Retweet someone elses tweet
	Route::post('/tweets/{tweet}/retweet/','RetweetController@store')
		->name('retweet');

	// Messages area - show all the messages.
	Route::get('/messages/','MessageController@index')
		->name('messages');

	// Send a message to a user
	Route::post('/messages/','MessageController@store');

	// Delete a message
	Route::delete('/message/{message}/delete/','MessageController@destroy')
		->name('destroy_message');
	
	// Explore the profiles of other users on Tweety. 
	Route::get('/explore/', 'ExploreController@index')
		->name('explore');

	// Likes - the user likes anothers post
	Route::post('/likes/{tweet}/','LikesController@store')
		->name('likes_tweet');
		
	// Profile area, view and update

	// Use the 'name' attribute in route/model binding instead of the primary key = user:name 
	Route::get('/profile/{user:username}/', 'ProfileController@show')
		->name('profile');
	
	// Show form to edit the profile
	Route::get('/profile/{user:username}/edit','ProfileController@edit')
		->name('edit_profile')
		->middleware('can:edit,user'); // Don't forget the wildcard.

	// Finally, update the users profile information. 	
	Route::patch('/profile/{user:username}','ProfileController@update')
		->name('update_profile');

	// Handles the follow/unfollow on a toggle method.
	Route::post('/profile/{user:username}/follow/','FollowsController@store')
		->name('follow');

	// Notifications start here.
	Route::get('/notifications/user/', 'UserNotificationsController@show')
		->name('notifications');
	
	// Logs you out & directs to the homepage.
	Route::post('/logout', 'LoginController@logout');
});

Auth::routes();

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Message extends Model
{
	public $guarded = []; // Allow all, we'll sort on input.

    /**
     * 	Get the user instance of the message.
     * @return [type] [description]
     */
    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    /**
     * 	The username of the sender of the message. 
     * @return [type] [description]
     */
    public function getSenderAttribute()
    {
    	return $this->user->username;
    }

    /**
     * 	The username of the person the message is for. 
     * @return [type] [description]
     */
    public function getReceiverAttribute()
    {
    	return User::find($this->message_user_id)
    			->username;
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Message;
use App\User;

// Used to notify for messages
use App\Notifications\MessageReceived;

class MessageController extends Controller
{
	/**
	 * Get all the messages and the form to message.
     * 
	 */
    public function index()
    {
        // Paginate the received messages
        $received = auth()
            ->user()
            ->received_messages()
            ->latest()
            ->paginate(2);

        // Paginate the sent messages
        $sent = auth()
            ->user()
            ->sent_messages()
            ->latest()
            ->paginate(2);

    	// Return a view with the messages. 
    	return view('messages.index', [
            'received'=>$received,
            'sent'=>$sent],
        );
    }

    /**
     * Validate and save the message sent.
     * @return Retdirects back to the message view. 
     */
    public function store()
    {
    	// Validate the message. 
		request()->validate([
    		'user'=>'required',
    		'message'=>['required','string','max:255','min:10']
    	]);

  		// Store the message in the table. 
    	Message::create([
    		'user_id'=>auth()->user()->id,
    		'message_user_id'=>request('user'),
    		'message'=>request('message')
    	]);

        // Notify this user of a new message sent to them.
        $this->user = User::find(request('user'));

        // Notify the user they have a new message. Grab some details for the email later. 
        $this->user->notify(new MessageReceived(request()->all(), $this->user));

    	// Reirect to the messages view. 
    	return redirect()->route('messages');
    }

    /**
     * Remove the message.
     * @param  [string] $message This is the id of the message.
     */
    public function destroy($message)
    {
    	// Find and remove the message
    	Message::find($message)->delete(); // delete() on controller/ detach() on model. 

    	// Redirect to the messages view. 
    	return redirect()->route('messages');
    }
}

resources/views/messages/index.blade.php
<x-app>

<h2 class="font-bold text-2xl mb-4">Messages for: {{ucfirst(current_user()->username)}}</h2>

	<h3 class="font-bold text-xl mb-5">
		Send a new message:
	</h3>


<div class="border border-blue-400 rounded-lg p-6 mb-5">

    <form method="POST" action="/messages/">

        @csrf

		<div class="mt-5 mb-5 border border-gray-100">
			<textarea class="w-full p-7" rows="5" name="message" id="message" placeholder="What do you want to say?" required>{{old('message')}}</textarea>
		</div>

		<div>

		    <select name="user" mb-4 required class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-state">

			  <option value="">Please select a user</option>

			  <!-- Only allow the user to message someone that follows them -->
		      @foreach(current_user()->getFollowers AS $follows)
		      	<option value="{{$follows['id']}}">
		      		{{$follows['name']}} | {{$follows['username']}}
		      	</option>
		      @endforeach
		    
		    </select>

    	</div>

    	@error('message')
			<p class="text-red-500 font-bold mt-5 mb-5">{{$message}}</p>
		@enderror

		@error('user')
			<p class="text-red-500 font-bold mt-5 mb-5">{{$message}}</p>
		@enderror

        <hr class="my-4">

        <footer class="flex justify-between">

            <img class="mr-2 rounded-full" width="50" height="50" src="{{auth()->user()->avatar}}" alt=""/>

            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 ml-2 mt-4 px-4 rounded" 
            type="submit">
            Send message
            </button>
        </footer> 
    </form>
</div> 

@error('text')

<div class="mb-5 text-red-500 font-bold text-center">
        <p>{{$message}}</p>
</div>

@enderror


	<h3 class="font-bold text-xl mb-5">
		Received messages
	</h3>

	@forelse($received AS $message)
	
		<div class="border border-gray-300 rounded-lg p-5 border-blue-200">	
		
			<div class="mb-4">
				
					<p class="mb-5 font-bold">Message sender: {{$message->sender}}</p>
					<p>{{$message['message']}}</p>

					<hr class="mt-3"/>
					
					<div class="mt-3 flex justify-between">
						<p>{{$message['created_at']->diffForHumans()}} on </p>
						<p>{{$message['created_at']->format('d/m/Y H:i\h\r\s')}}</p>
						
						
						<form method="POST" action="/message/{{$message->id}}/delete/">
							
							@csrf
							@method('delete')

							<i class="fa fa-trash" aria-hidden="true"></i>
							<button>
								<p class="text-red-900"> Delete message</p>
							</button>
						</form>
					</div>
			</div>
		</div>
		<br/>
		@empty
			
		<p>You haven't received any messages.</p>
	
	@endforelse

	{{ $received->links() }}

	<hr class="mb-5 mt-5"/>


	<h3 class="font-bold text-xl mb-5">
		Sent messages
	</h3>

	@forelse($sent AS $message)
	
		<div class="border border-gray-300 rounded-lg p-5 border-blue-200">	
		
			<div class="mb-4">
				
					<p class="mb-5 font-bold">Message sent to: {{$message->receiver}}</p>
					<p>{{$message['message']}}</p>

					<hr class="mt-3"/>
					
					<div class="mt-3 flex justify-between">
						<p>{{$message['created_at']->diffForHumans()}} on </p>
						<p>{{$message['created_at']->format('d/m/Y H:i\h\r\s')}}</p>
						
						<form method="POST" action="/message/{{$message->id}}/delete/">
							
							@csrf
							@method('delete')

							<i class="fa fa-trash" aria-hidden="true"></i>
							<button>
								<p class="text-red-900"> Delete message</p>
							</button>
						</form>
					</div>
			</div>
		</div>
		<br/>
		@empty
			
		<p>You haven't received any messages.</p>
	
	@endforelse

	{{ $sent->links() }}

</x-app>